//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ_import
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ_import()
        {
            this.товар_заказ = new HashSet<товар_заказ>();
        }
    
        public int id { get; set; }
        public System.DateTime Дата_заказа { get; set; }
        public System.DateTime Дата_доставки { get; set; }
        public int id_пункт_выдачи { get; set; }
        public string ФИО_авторизованного_клиента { get; set; }
        public int Код_для_получения { get; set; }
        public Nullable<int> id_пользователя { get; set; }
        public Nullable<int> id_статус { get; set; }
    
        public virtual user_import user_import { get; set; }
        public virtual Пункты_выдачи_import Пункты_выдачи_import { get; set; }
        public virtual Статусы Статусы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<товар_заказ> товар_заказ { get; set; }
    }
}
