//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пункты_выдачи_import
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пункты_выдачи_import()
        {
            this.Заказ_import = new HashSet<Заказ_import>();
        }
    
        public int id { get; set; }
        public int индекс { get; set; }
        public string город { get; set; }
        public string улица { get; set; }
        public int дом { get; set; }

        public string ПолныйАдрес
        {
            get
            {
                return $"{город}, {улица}, д. {дом}";
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ_import> Заказ_import { get; set; }
    }
}
