//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class товар_заказ
    {
        public int id { get; set; }
        public int id_заказа { get; set; }
        public string id_товара { get; set; }
        public int количесвто { get; set; }
    
        public virtual Tovar Tovar { get; set; }
        public virtual Заказ_import Заказ_import { get; set; }
    }
}
