// <auto-generated />
namespace ozon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class efdvdfvdfvdf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(efdvdfvdfvdf));
        
        string IMigrationMetadata.Id
        {
            get { return "202510272046023_efdvdfvdfvdf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
