//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заявки()
        {
            this.Услуги_Заявки = new HashSet<Услуги_Заявки>();
        }
    
        public int id { get; set; }
        public System.DateTime Дата_создания { get; set; }
        public int id_клиента { get; set; }
        public string Телефон_клиента { get; set; }
        public string Email_клиента { get; set; }
        public string Тип_техники { get; set; }
        public string Модель { get; set; }
        public string Неисправность { get; set; }
        public Nullable<int> id_мастера { get; set; }
        public int id_статус { get; set; }
        public int Стоимость_работ { get; set; }
        public int Стоимость_запчастей { get; set; }
        public string column13 { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Мастера Мастера { get; set; }
        public virtual Статусы Статусы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Услуги_Заявки> Услуги_Заявки { get; set; }
    }
}
