//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Услуги_Заявки
    {
        public int id { get; set; }
        public int id_заявки { get; set; }
        public int id_услуги { get; set; }
    
        public virtual Заявки Заявки { get; set; }
        public virtual Услуги Услуги { get; set; }
    }
}
